name: Run Prettier Lints

on: [push, pull_request]

jobs:
  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Yarn
      uses: Borales/actions-yarn@master
      with:
        args: install
    - name: Prettier
      uses: Borales/actions-yarn@master
      - working-directory: javascript/
      with:
        args: run prettier-check
