name: Run Standard Lints

on:
  - push
  - pull_request

jobs:
  standard:
    name: Standard
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Bundle
      uses: CultureHQ/actions-bundler@master
      with:
        args: install
    - name: Standard
      uses: CultureHQ/actions-bundler@master
      with:
        args: exec standardrb --format progress
