name: Tests

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master

jobs:
  javascript_test:
    name: JavaScript Test Action
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [10, 12]
    steps:
    - uses: actions/checkout@master
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - name: Yarn
      run: yarn
      working-directory: javascript/
    - name: Run JavaScript Tests
      run: yarn run test
      working-directory: javascript/

  ruby_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@vmaster
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Bundle
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
    - name: Run ruby tests
      run: bin/ruby_test
