name: Tests

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master

jobs:
  javascript_test:
    name: JavaScript Test Action
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [10, 12]
    steps:
    - uses: actions/checkout@master
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - run: yarn
      working-directory: javascript/
    - run: yarn run test
      working-directory: javascript/
  ruby_test:
    name: Ruby Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Standard
      uses: CultureHQ/actions-bundler@master
      with:
        args: install && bin/ruby_test
